image: ubuntu:16.10

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq git build-essential kernel-package fakeroot libncurses5-dev libssl-dev ccache python3.5
  - git config --global user.email "max.ehr@gmail.com"
  - git config --global user.name "Max Ehrlich"
  - python3.5 setup-patches.py "$KERN_MSG_TITLE"
  - cp .config linux
  - cd linux

kernel:
  stage: build
  script: 
    - make olddefconfig
    - make clean
    - make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-acso
    - echo $CI_JOB_ID >> kern_job_id
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - kern_job_id
  only:
    - triggers
  artifacts:
    paths: 
      - ./*.deb
      - ./*.tar.gz
      - ./*.changes
      - ./*.dsc

pages:
  stage: deploy
  script:
    - git checkout pages
    - python3.5 splice_page.py "$KERN_MSG_TITLE"
    - cp index.html public/index.html
    - git add index.html
    - git commit -m "$KERN_MSG_TITLE"
    - git push
    - mv .public public
  cache:
    key: "$CI_PIPELINE_ID"
  only:
    - triggers
  artifacts:
    paths:
    - public
