image: ubuntu:17.10

variables:
  DOCKER_DRIVER: overlay2

stages:
  - deploy

# These have to be done before pretty much all jobs
before_script:
  - apt-get update
  - apt-get install -y python3.5 git

# Generate a new json "api" for the homepage
pages:
  stage: deploy
  script:
    # Merge CI changes from master branch
    - git merge master

    # Generate the new API
    - mkdir public
    - python3 scripts/db_to_web.py public/kernel.json
    - cp index.html public/index.html
  only:
    - triggers
  artifacts:
    paths:
      - public
