image: ubuntu:18.04

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - log

# These have to be done before pretty much all jobs
before_script:
  - apt-get update
  - apt-get install -y python3.6 git

# Patch and build the kernel
kernel:
  stage: build
  script:
    # Install dependencies
    - export DEBIAN_FRONTEND=noninteractive
    - >
      apt-get install -y
      build-essential
      kernel-package
      fakeroot
      libncurses5-dev
      libssl-dev
      ccache
      libelf-dev
      bsdmainutils
      bison
      flex
      dh-systemd
      kernel-wedge
      makedumpfile
      libnewt-dev
      libiberty-dev
      rsync
      libdw-dev
      libpci-dev
      pkg-config
      libunwind8-dev
      liblzma-dev
      libaudit-dev
      python-dev
      gawk
      libudev-dev
      autoconf
      automake
      libtool
      uuid-dev
      binutils-dev
      transfig
      sharutils
      asciidoc
      debhelper
      docbook-utils

    # Download kernel source and patch it
    - python3.6 scripts/setup_patches.py "$KERN_MSG_TITLE"
    - source workspace

    # Build the kernel
    - export CCACHE_DIR=$KERNEL_WORKSPACE/ccache
    - cp $KERNEL_WORKSPACE/kernel_config $KERNEL_WORKSPACE/linux/.config
    - pushd $KERNEL_WORKSPACE/linux
    - rm -rf .git
    - make olddefconfig
    - make clean
    - make CC="ccache gcc" -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-acso
    - ccache -s
    - popd

    # Store the build artifacts
    - cp $KERNEL_WORKSPACE/*.deb .
    - cp $KERNEL_WORKSPACE/*.tar.gz .
    - cp $KERNEL_WORKSPACE/*.changes .
    - cp $KERNEL_WORKSPACE/*.dsc .

    # Save the job ID for later
    - echo $CI_JOB_ID > BUILD_JOB_ID
  only:
    - triggers
  artifacts:
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.changes
      - ./*.dsc
      - BUILD_JOB_ID

# Log the build in git
log:
  stage: log
  script:
    # Install curl to trigger the pages job
    - apt-get install -y curl

    # Update the database with the built kernel informtion
    - BUILD_JOB_ID=$(cat BUILD_JOB_ID)
    - python3.6 scripts/log_build.py "$KERN_MSG_TITLE" $BUILD_JOB_ID

    # Store ssh push credentials
    - mkdir -p ~/.ssh
    - echo "$CI_PUSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts

    # Configure git
    - git config --global user.email max.ehr@gmail.com
    - git config --global user.name Queuecumber
    - git remote -v
    - git checkout $CI_COMMIT_REF_NAME

    # Commit the new database and store it on the server
    - git add db/*
    - "git commit -m \"[CI: $CI_PIPELINE_ID] Add $KERN_MSG_TITLE\""
    - git remote set-url origin git@gitlab.com:Queuecumber/linux-acs-override.git
    - gt pull --rebase
    - git push

    # Trigger pages to rebuild
    - curl --request POST --form "token=$CI_JOB_TOKEN" https://gitlab.com/api/v4/projects/2887717/ref/pages/trigger/pipeline
  only:
    - triggers