image: ubuntu:17.10

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

# These have to be done before pretty much all jobs
before_script:
  - apt-get update
  - apt-get install -y python3.5 git

# Make sure the updated db is passed down the pipeline
cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - db

# Patch and build the kernel
kernel:
  stage: build
  script:
    # Install dependencies
    #- apt-get install -y build-essential kernel-package fakeroot libncurses5-dev libssl-dev ccache libelf-dev bsdmainutils

    # Download kernel source and patch it
    - python3 scripts/setup_patches.py "$KERN_MSG_TITLE"
    - source workspace

    # Build the kernel
#    - cp $KERNEL_WORKSPACE/kernel_config $KERNEL_WORKSPACE/linux/.config
#    - pushd $KERNEL_WORKSPACE/linux
#    - make olddefconfig
#    - make clean
#    - make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-acso
#    - popd

    # Store the build artifacts
    - cp $KERNEL_WORKSPACE/*.deb .
    - cp $KERNEL_WORKSPACE/*.tar.gz .
    - cp $KERNEL_WORKSPACE/*.changes .
    - cp $KERNEL_WORKSPACE/*.dsc .

    # Update the database with the built kernel informtion
    - python3 scripts/log_build.py "$KERN_MSG_TITLE" $CI_JOB_ID
  only:
    - triggers
  artifacts:
    paths:
      - ./*.deb
      - ./*.tar.gz
      - ./*.changes
      - ./*.dsc

# Generate a new json file for the homepage
pages:
  stage: deploy
  script:
    # Generate the public site data
    - mkdir public
    - python3 scripts/db_to_web.py public/kernel.json
    - cp index.html public/index.html

    # Log the successful build in git
    - mkdir -p ~/.ssh
    - echo "$CI_PUSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - git config --global user.email max.ehr@gmail.com
    - git config --global user.name Queuecumber
    - git remote -v
    - git checkout $CI_COMMIT_REF_NAME
    - git add db/*
    - "git commit -m \"[CI: $CI_PIPELINE_ID] Add $KERN_MSG_TITLE\""
    - git remote set-url origin git@gitlab.com:Queuecumber/linux-acs-override.git
    - git push
  only:
    - triggers
  artifacts:
    paths:
    - public
