image: ubuntu:18.04

variables:
  DOCKER_DRIVER: overlay2

stages:
  - deploy

# These have to be done before pretty much all jobs
before_script:
  - apt-get update
  - apt-get install -y python3.6 git

# Generate a new json "api" for the homepage
pages:
  stage: deploy
  script:
    # Copy static site data to public directory
    - mkdir public
    - cp notices.json public/notices.json
    - cp index.html public/index.html

    # Merge CI changes from master branch
    - git config --global user.email max.ehr@gmail.com
    - git config --global user.name Queuecumber
    - git checkout master

    # Generate the new API
    - python3.6 scripts/db_to_web.py public/kernel.json
  artifacts:
    paths:
      - public
