image: ubuntu:16.10

before_script:
  - apt-get update -qq && apt-get install -y -qq git build-essential kernel-package fakeroot libncurses5-dev libssl-dev ccache python3.5
  - git config --global user.email "max.ehr@gmail.com"
  - git config --global user.name "Max Ehrlich"
  - python3.5 setup-patches.py "$KERN_MSG_TITLE"
  - cp .config linux
  - cd linux

kernel:
  stage: build
  script: 
    - make olddefconfig
    - make clean
    - make -j `getconf _NPROCESSORS_ONLN` deb-pkg LOCALVERSION=-acso
  only:
    - triggers
  artifacts:
    paths: 
      - *.deb
      - *.tar.gz
      - *.changes
      - *.dsc
